---
title: About Jon
---

Jonathan ("Jon") Brock was born in 1984 in Kent, Washington. He attended St. Anthony Catholic Elementary School in Renton, WA for grades K-8; John F. Kennedy Memorial High School in Burien, WA for grades 9-12; and Seattle University in Seattle, WA for undergraduate studies. He completed his Bachelor of Arts in Humanities in June 2007.  

Upon graduation, Jon took time to consider his future career path. In the interim years, Jon worked at an independent bookstore, at a legal service processing company, for a valet parking company (both in Seattle and San Francisco), Starbucks, and as a dog walker.  

Two years after moving to San Francisco from Seattle, Jon decided to commit himself to some relevant volunteer work. He started in January 2014 with Magnet in the Castro, the clinical arm of San Francisco AIDS Foundation. After six months' worth of data entry of clinical HIV testing data, Jon decided he wanted to do more. He took the week-long training provided by the San Francisco Department of Public Health to become a certified HIV test counselor.

In 2015, Jon was hired by the San Francisco Department of Public Health (SFDPH) as a part-time Study Recruiter within the Substance Use Research Unit (SURU). After a few months of recruiting, a new and exciting opportunity presented itself in the form of a Research Associate position within the HIV Surveillance and Epidemology Section of (SFDPH).

In late 2017, after two full years of working in HIV surveillance, Jon was offered a Disease and Research Intervention Specialist position back in his hometown of Seattle; at the Public Health Seattle and King County (PHSKC) STD Clinic at Harborview. Jon moved his entire life back up to Seattle, and subsequently moved it back to San Francisco four months later.

In January 2018, Jon was offered admission into the Columbia University Mailman School of Public Health's Master of Public Health (MPH) degree program within the Department of Epidemiology. He accepted the offer in March 2018 after attending the Admitted Students Day.

Upon returning to San Francisco, Jon quickly got back on his feet, and started working as both an HIV Re-Linkage to Care Specialist and a Lab Tech/Phlebotomist at the San Francisco City Clinic (SFCC) and Strut (formerly Magnet of the San Francisco AIDS Foundation), respectively.

In August 2018, Jon moved across the country to New York City to start his graduate studies in epidemiology. His summer 2019 practicum was completed at SFDPH in the HIV Surveillance and Epidemiology section focusing on a secondary analysis of demographic and sexual indicators of HIV+ individuals receiving screenings for GT, CT, and syphilis in the prior 12 months.

Jon is currently completing his third semester of graduate school, with an expected graduation date of May 2020.