---
title: "Plotly Plots"
output:
    flexdashboard::flex_dashboard:
        orientation:  columns
        vertical_layout: fill
---

```{r load packages, include = FALSE}
library(tidyverse)
library(plotly)
library(flexdashboard)
```

Column {data-width=575}
-----------------------------------------------------------------------

### Top 10 **NYC** Food Establishments by Store Count

```{r plot A}
p8105.datasets::rest_inspec %>%
    count(dba, sort = TRUE) %>% 
    top_n(10) %>% 
    plot_ly(y = ~n, color = ~dba, type = "bar")
```

Column {data-width=425}
-----------------------------------------------------------------------

### Range of Food Inspection Scores for Central Harlem's Dunkin Donuts (lower scores are better)

```{r plot B}
p8105.datasets::rest_inspec %>%
    filter(boro == "MANHATTAN", dba == "DUNKIN' DONUTS", zipcode == c("10026", "10027", "10030", "10037", "10039")) %>% 
    drop_na(score) %>%
    plot_ly(y = ~score, color = ~street, type = "box")
```

### Top 12 Food Establishment Types in **Staten Island** by Store Count

```{r plot C}
p8105.datasets::rest_inspec %>%
    filter(boro == "STATEN ISLAND") %>% 
    count(cuisine_description, sort = TRUE) %>% 
    top_n(12) %>% 
    plot_ly(x = ~cuisine_description, y = ~n, type = "scatter", mode = "markers", color = ~cuisine_description, size = 10, showlegend = F)
```