---
title: "<span style='font-size: 25px'>Publications</style>"
---

***

#### **Conference Abstracts**  
Sachdev, D.D., **Brock, J.**, Chen, M.J., Cohen, S.E., Scheer, S. Re-Linkage Outcomes of Not-in-Care People Living with HIV Identified through HIV-TRACE in San Francisco. National HIV Prevention Conference, Atlanta, GA, 2019. Accepted November 18, 2018. [[link]](https://www.cdc.gov/nhpc/pdf/NHPC-2019-Abstract-Book.pdf) (p.422)  

***  

#### **Journal Publications**  
Hughes, A.J., Rector, A., Jimenez, V., **Brock, J.**, Scheer, S. Cumulative Plasma HIV Burden Disparities among Adults in HIV Care: Implications for HIV Transmission in the Era of Treatment as Prevention. AIDS. 2018 Aug. 32(13):1881-1889 [[link]](https://www.ncbi.nlm.nih.gov/pubmed/29894384)  

***  

#### **Surveillance Reports**  
Contributions to “2017 HIV Epidemiology Annual Report,” San Francisco Department of Public Health Population Health Division (PHD) [[link]](https://www.sfdph.org/dph/files/reports/RptsHIVAIDS/AnnualReport2017-Green-20180904-Web.pdf)  
Contributions to “2016 HIV Epidemiology Annual Report,” San Francisco Department of Public Health Population Health Division (PHD)  
Contributions to “2015 HIV Epidemiology Annual Report,” San Francisco Department of Public Health Population Health Division (PHD) [[link]](https://www.sfdph.org/dph/files/reports/RptsHIVAIDS/AnnualReport2015-20160831.pdf)  

***  

#### **Medical Monitoring Project Reports**  
Contributions to “Behavioral and Clinical Characteristics of Persons Living with Diagnosed HIV 2015-2016,” HIV Epidemiology Section – Applied Research, Community Health Epidemiology, and Surveillance [[link]](https://www.sfdph.org/dph/files/reports/RptsHIVAIDS/SF-MMP-15-16-Report.pdf)  
Contributions to “Behavioral and Clinical Characteristics of Persons Receiving HIV Medical Care 2013-2014,” HIV Epidemiology Section – Applied Research, Community Health Epidemiology, and Surveillance [[link]](https://www.sfdph.org/dph/files/reports/RptsHIVAIDS/SFMMP1314Report.pdf)  
Contributions to “Behavioral and Clinical Characteristics of Persons Receiving HIV Medical Care 2011-2012,” HIV Epidemiology Section – Applied Research, Community Health Epidemiology, and Surveillance [[link]](https://www.sfdph.org/dph/files/reports/RptsHIVAIDS/SF-MMP-11-12-Report.pdf)