---
title: "<span style='font-size: 25px'>Volunteer Experience</style>"
---
***

#### **San Francisco AIDS Foundation ** 

##### *Phlebotomist (07/2016 – 10/2017)*  
• Performed high volume venipuncture with exceptional accuracy  
• Triaged patients for appropriate services, including PrEP, nPEP, and HIV/STI testing and treatment  

##### *HIV Test Counselor (07/2014 – 06/2017)*  
• Provided harm reduction counseling for men who have sex with men  
• Disseminated HIV/STI information to patients in a culturally appropriate manner  
• Performed throat and rectal swabs for STI screenings  
• Provided training for new HIV test counselors  
• Disclosed rapid HIV test results to patients  

##### *Data Entry Clerk (01/2014 – 09/2014)*  
• Entered weekly HIV testing data into a secure online portal for the CDC pertaining to the sexual  
behaviors and habits of men who have sex with men  
	
***

#### **San Francisco Community Health Center (Formerly API Wellness Center)**  

##### *HIV Test Counselor (08/2015 – 12/2015)*
• Provided harm reduction counseling for Asian and Pacific Islander men who identify as gay, bisexual, and transgender  
• Disseminated HIV/STI information to patients in a culturally appropriate manner  
• Disclosed rapid HIV test results to patients  
• Performed duties in non-clinical settings (gay bars, Folsom Street Fair, etc.)  